services:
    # default configuration for services in *this* file
    _defaults:
        autowire: false      # Automatically injects dependencies in your services.
        autoconfigure: false # Automatically registers your services as commands, event subscribers, etc.

    Xact\JSRoutingBundle\Extractor\RoutingExtractor:
        autowire: true
        $cacheDir: '%kernel.cache_dir%'
        $appEnv: '%env(string:APP_ENV)%'
